### ISSUE TITLE
A question about code implementation

### ISSUE THREAD

**Issue by Jedges** [Ironprop-Stone/DeepGate2#2]
According to the description in the paper, when aggregating the function embedding of AND and NOT nodes, the structural  and functional embedding of their predecessor nodes are used for calculation. But when doing this in lines 142 and 159 of the mlp_gate.py file, why is only the function encoding used for updating the not node? Maybe I didn't fully understand your code.
I hope to get your reply. Thanks!

**Comment by zshi0616** [comment]
Hi, thanks for your interests in DeepGate2. 
When we update the functional embeddings for multi-fanin gates, we need to consider the functionality of fanins (the functional embedding of predecessors) and the correlation between these fanins (represented by the structural embeddings of predecessors). Therefore, we update AND embedding as shown in Line 142. For NOT gate in Line 159, there is only one fanin, so no need to add structural embeddings. 
Thanks!

**Comment by Jedges** [comment]
![Snipaste_2024-06-27_16-22-31](https://github.com/zshi0616/DeepGate2/assets/75368234/09c51fa6-cfe4-4cc8-b0eb-1767a8da7bbf)
Thank you for your quick reply. I understand what you mean. I think the description in the paper may be misleading. According to formula (7), it also uses the structural information of the predecessor node when updating the not node.

**Comment by zshi0616** [comment]
Hi, according to our experiments, these two methods (w. hs, w./o. hs) have the similar results, we just remove structural embeddings in this implementation. 
Thanks

**Comment by Jedges** [comment]
Thank you for your reply!  This solved my question successfully.
